### ISSUE TITLE
Error when processing a year's worth of data, rather than 3-6 months.

### ISSUE THREAD

**Issue by boland1992** [bgoutorbe/seismic-noise-tomography#16]
After processing a year's worth of waveforms for 77 stations here in Australia, the code doesn't want to process the dispersion curves using dispersion_curves.py. The maximum I can get for this working so far has been 44 stations for 4 months. Any longer than that and I get the following error:

/storage/ANT/AMBIENT-NOISE-TOMOGRAPHY/pysismo/pscrosscorr.py:2499: DeprecationWarning: numpy boolean negative (the unary `-` operator) is deprecated, use the bitwise_xor (the `^` operator) or the logical_xor function instead.
  notnan = -(np.isnan(vgarray) | np.isnan(amplarray))

Traceback (most recent call last):
  File "dispersion_curves.py", line 102, in <module>
    xc.FTANs(suffix=suffix, whiten=False, normalize_ampl=True, logscale=True)
  File "/storage/ANT/AMBIENT-NOISE-TOMOGRAPHY/pysismo/pscrosscorr.py", line 1982, in FTANs
    **kwargs)
  File "/storage/ANT/AMBIENT-NOISE-TOMOGRAPHY/pysismo/pscrosscorr.py", line 1056, in FTAN_complete
    **kwargs)
  File "/storage/ANT/AMBIENT-NOISE-TOMOGRAPHY/pysismo/pscrosscorr.py", line 877, in FTAN
    fp=inst_periods[~masknan])
  File "/home/abe/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1191, in interp
    return compiled_interp(x, xp, fp, left, right)
ValueError: array of sample points is empty

The to part of the error (from /storage to (amplarray)) ) comes up thousands of times in a row until the final traceback error. Do you have any advice? Thank you for your time.

**Comment by bgoutorbe** [comment]
Hi,
I made a correction so that the DeprecationWarning part (which shows up thousands of times) won't appear any more.
As for the ValueError, I think it comes from an earlier version of the code. Please update and it should be working fine.

On a side note, you can check the FTAN and dispersion curves on individual pairs, from a collection of cross-correlations 'xc', by doing this:
```
xc.STA01.STA02.plot_FTAN()
```

In order to load a collection of cross-corr, do the following:
```
from pysismo import pscrosscorr
xc = pscrosscorr.load_pickled_xcorr_interactive()
```

or run pscrosscorr.py as a script, from the directory containing pysismo:
```
python -u -i pysismo/pscrosscorr.py
```
